export const runDefaultConfig = {
  url: undefined,
  label: undefined,
  runs: 2,
  location: "gce-europe-west4:Chrome.4G",
  video: 1,
  lighthouse: 1,
  f: "json",
  // latency: undefined,
  // plr: undefined,
  // script: undefined,
  // block: undefined,
  // private: undefined,
  // width: undefined,
  // height: undefined,
  // browser_width: undefined,
  // browser_height: undefined,
  // mobileDevice: undefined,
  // type: undefined,
  // timeline: undefined,
  // timelineStack: undefined,
  // profiler: undefined,
  // fvonly: undefined,
  // domelement: undefined,
  // web10: undefined,
  // login: undefined,
  // password: undefined,
  // authType: undefined,
  // r: undefined,
  // pingback: undefined,
  // bwDown: undefined,
  // bwUp: undefined,
  // tcpdump: undefined,
  // noopt: undefined,
  // noimages: undefined,
  // noheaders: undefined,
  // pngss: undefined,
  // iq: undefined,
  // clearcerts: undefined,
  // mobile: undefined,
  // keepua: undefined,
  // uastring: undefined,
  // dpr: undefined,
  // mv: undefined,
  // medianMetric: undefined,
  // cmdline: undefined,
  // htmlbody: undefined,
  // tsview_id: undefined,
  // custom: undefined,
  // tester: undefined,
  // affinity: undefined,
  // ignoreSSL: undefined,
  // appendua: undefined,
  // injectScript: undefined,
  // disableAVIF: undefined,
  // disableWEBP: undefined,
  // disableJXL: undefined,
  // dtShaper: undefined,
  // wappalyzer: undefined,
  // metadata: undefined,
  // axe: undefined,
  // axe_categories: undefined,
};
